url: https://cloudhacks.org

# Site settings
title: CloudHacks
email: csciclub@csci.club
description: "CloudHacks is 24-hour student-run Hackathon hosted at St. Cloud State University."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cloudhacks
  - title: facebook
    url:
  - title: github
    url: http://github.com/csciclub

# Postal address (add as many lines as necessary)
address:
  - line: 720 4th Ave S
  - line: St. Cloud, MN 56301

# Build settings
markdown: kramdown
permalink: pretty
